import { Applicant, ApplicantResponse } from "@/types";

export const mockApplicants: Applicant[] = [
  {
    id: 1,
    fullName: "John Doe",
    email: "john.doe@email.com",
    phone: "+1 (555) 123-4567",
    avatar: "JD",
    appliedDate: "2024-01-15",
    status: "Pending",
    jobTitle: "Frontend Developer",
    experience: "3 years",
    skills: ["React", "TypeScript", "JavaScript", "HTML", "CSS"],
    resumeUrl: "/resumes/john-doe-resume.pdf",
    coverLetter: "I am excited to apply for the Frontend Developer position...",
    rating: 4.5,
    notes: "Strong technical skills, good communication",
  },
  {
    id: 2,
    fullName: "Jane Smith",
    email: "jane.smith@email.com",
    phone: "+1 (555) 234-5678",
    avatar: "JS",
    appliedDate: "2024-01-14",
    status: "Reviewing",
    jobTitle: "UI/UX Designer",
    experience: "5 years",
    skills: ["Figma", "Adobe XD", "Sketch", "Prototyping", "User Research"],
    resumeUrl: "/resumes/jane-smith-resume.pdf",
    coverLetter: "With 5 years of experience in UI/UX design...",
    rating: 4.8,
    notes: "Excellent portfolio, creative thinker",
  },
  {
    id: 3,
    fullName: "Mike Johnson",
    email: "mike.johnson@email.com",
    phone: "+1 (555) 345-6789",
    avatar: "MJ",
    appliedDate: "2024-01-13",
    status: "Interview",
    jobTitle: "Backend Developer",
    experience: "4 years",
    skills: ["Node.js", "Python", "PostgreSQL", "MongoDB", "AWS"],
    resumeUrl: "/resumes/mike-johnson-resume.pdf",
    coverLetter: "I am passionate about backend development...",
    rating: 4.2,
    notes: "Technical interview scheduled for next week",
  },
  {
    id: 4,
    fullName: "Sarah Wilson",
    email: "sarah.wilson@email.com",
    phone: "+1 (555) 456-7890",
    avatar: "SW",
    appliedDate: "2024-01-12",
    status: "Hired",
    jobTitle: "Product Manager",
    experience: "6 years",
    skills: [
      "Product Strategy",
      "Agile",
      "Analytics",
      "Leadership",
      "Roadmapping",
    ],
    resumeUrl: "/resumes/sarah-wilson-resume.pdf",
    coverLetter: "I bring 6 years of product management experience...",
    rating: 4.9,
    notes: "Excellent candidate, offer accepted",
  },
  {
    id: 5,
    fullName: "David Brown",
    email: "david.brown@email.com",
    phone: "+1 (555) 567-8901",
    avatar: "DB",
    appliedDate: "2024-01-11",
    status: "Rejected",
    jobTitle: "DevOps Engineer",
    experience: "2 years",
    skills: ["Docker", "Kubernetes", "CI/CD", "Linux", "Monitoring"],
    resumeUrl: "/resumes/david-brown-resume.pdf",
    coverLetter: "I am interested in the DevOps Engineer position...",
    rating: 3.8,
    notes: "Lacks sufficient experience for senior role",
  },
  {
    id: 6,
    fullName: "Emily Davis",
    email: "emily.davis@email.com",
    phone: "+1 (555) 678-9012",
    avatar: "ED",
    appliedDate: "2024-01-10",
    status: "Pending",
    jobTitle: "Data Scientist",
    experience: "3 years",
    skills: ["Python", "R", "Machine Learning", "SQL", "Statistics"],
    resumeUrl: "/resumes/emily-davis-resume.pdf",
    coverLetter: "I am excited about the Data Scientist opportunity...",
    rating: 4.3,
    notes: "Strong analytical skills, good fit for team",
  },
  {
    id: 7,
    fullName: "Alex Chen",
    email: "alex.chen@email.com",
    phone: "+1 (555) 789-0123",
    avatar: "AC",
    appliedDate: "2024-01-09",
    status: "Reviewing",
    jobTitle: "Mobile Developer",
    experience: "4 years",
    skills: ["React Native", "Flutter", "iOS", "Android", "Swift"],
    resumeUrl: "/resumes/alex-chen-resume.pdf",
    coverLetter: "I have extensive experience in mobile development...",
    rating: 4.6,
    notes: "Impressive mobile app portfolio",
  },
  {
    id: 8,
    fullName: "Lisa Garcia",
    email: "lisa.garcia@email.com",
    phone: "+1 (555) 890-1234",
    avatar: "LG",
    appliedDate: "2024-01-08",
    status: "Interview",
    jobTitle: "Marketing Manager",
    experience: "5 years",
    skills: [
      "Digital Marketing",
      "SEO",
      "Content Strategy",
      "Analytics",
      "Campaign Management",
    ],
    resumeUrl: "/resumes/lisa-garcia-resume.pdf",
    coverLetter: "I am passionate about marketing and brand building...",
    rating: 4.4,
    notes: "Second interview scheduled",
  },
  // Add more applicants to test pagination
  {
    id: 9,
    fullName: "Robert Taylor",
    email: "robert.taylor@email.com",
    phone: "+1 (555) 901-2345",
    avatar: "RT",
    appliedDate: "2024-01-07",
    status: "Pending",
    jobTitle: "Full Stack Developer",
    experience: "4 years",
    skills: ["React", "Node.js", "MongoDB", "AWS", "Docker"],
    resumeUrl: "/resumes/robert-taylor-resume.pdf",
    coverLetter: "I am a full stack developer with 4 years of experience...",
    rating: 4.1,
    notes: "Good technical background",
  },
  {
    id: 10,
    fullName: "Maria Rodriguez",
    email: "maria.rodriguez@email.com",
    phone: "+1 (555) 012-3456",
    avatar: "MR",
    appliedDate: "2024-01-06",
    status: "Reviewing",
    jobTitle: "QA Engineer",
    experience: "3 years",
    skills: ["Selenium", "Jest", "Cypress", "Manual Testing", "API Testing"],
    resumeUrl: "/resumes/maria-rodriguez-resume.pdf",
    coverLetter: "I have 3 years of experience in quality assurance...",
    rating: 4.0,
    notes: "Strong testing skills",
  },
  {
    id: 11,
    fullName: "James Wilson",
    email: "james.wilson@email.com",
    phone: "+1 (555) 123-4567",
    avatar: "JW",
    appliedDate: "2024-01-05",
    status: "Interview",
    jobTitle: "System Administrator",
    experience: "5 years",
    skills: ["Linux", "Windows Server", "Networking", "Security", "Cloud"],
    resumeUrl: "/resumes/james-wilson-resume.pdf",
    coverLetter: "I am an experienced system administrator...",
    rating: 4.3,
    notes: "Technical interview completed",
  },
  {
    id: 12,
    fullName: "Anna Thompson",
    email: "anna.thompson@email.com",
    phone: "+1 (555) 234-5678",
    avatar: "AT",
    appliedDate: "2024-01-04",
    status: "Hired",
    jobTitle: "Business Analyst",
    experience: "4 years",
    skills: ["Requirements Analysis", "SQL", "Excel", "Power BI", "Agile"],
    resumeUrl: "/resumes/anna-thompson-resume.pdf",
    coverLetter: "I am a business analyst with strong analytical skills...",
    rating: 4.7,
    notes: "Excellent candidate, offer accepted",
  },
  {
    id: 13,
    fullName: "Michael Lee",
    email: "michael.lee@email.com",
    phone: "+1 (555) 345-6789",
    avatar: "ML",
    appliedDate: "2024-01-03",
    status: "Rejected",
    jobTitle: "Security Engineer",
    experience: "2 years",
    skills: [
      "Cybersecurity",
      "Penetration Testing",
      "SIEM",
      "Firewall",
      "Compliance",
    ],
    resumeUrl: "/resumes/michael-lee-resume.pdf",
    coverLetter: "I am interested in the Security Engineer position...",
    rating: 3.5,
    notes: "Needs more experience",
  },
  {
    id: 14,
    fullName: "Sophie Martin",
    email: "sophie.martin@email.com",
    phone: "+1 (555) 456-7890",
    avatar: "SM",
    appliedDate: "2024-01-02",
    status: "Pending",
    jobTitle: "Content Writer",
    experience: "3 years",
    skills: [
      "Content Writing",
      "SEO",
      "Copywriting",
      "Social Media",
      "WordPress",
    ],
    resumeUrl: "/resumes/sophie-martin-resume.pdf",
    coverLetter: "I am a creative content writer with 3 years of experience...",
    rating: 4.2,
    notes: "Good writing samples",
  },
  {
    id: 15,
    fullName: "Daniel Kim",
    email: "daniel.kim@email.com",
    phone: "+1 (555) 567-8901",
    avatar: "DK",
    appliedDate: "2024-01-01",
    status: "Reviewing",
    jobTitle: "DevOps Engineer",
    experience: "4 years",
    skills: ["Kubernetes", "Docker", "Jenkins", "Terraform", "AWS"],
    resumeUrl: "/resumes/daniel-kim-resume.pdf",
    coverLetter: "I am a DevOps engineer passionate about automation...",
    rating: 4.5,
    notes: "Strong DevOps background",
  },
];

export const mockApplicantResponse = (
  page: number = 1,
  limit: number = 10
): ApplicantResponse => {
  const startIndex = (page - 1) * limit;
  const endIndex = startIndex + limit;
  const applicants = mockApplicants.slice(startIndex, endIndex);

  return {
    applicants,
    total: mockApplicants.length,
    page,
    totalPages: Math.ceil(mockApplicants.length / limit),
    hasMore: endIndex < mockApplicants.length,
  };
};
